#!/usr/bin/env bash
#
# Tejam one-shot deploy script for Ubuntu 22.04 / 24.04 on an Azure VM.
#
# What it does:
#   1. Installs Python 3, Node 20, Nginx, Certbot, and build tools
#   2. Creates a Python venv and installs backend requirements
#   3. Generates backend/.env on first run (with random SECRET_KEY / JWT_SECRET_KEY)
#   4. Builds the React frontend (npm install && npm run build)
#   5. Installs and starts a systemd service (tejam.service) running Gunicorn
#   6. Installs an Nginx site that serves the React build and proxies /api + /uploads
#   7. Opens UFW for HTTP/HTTPS/SSH
#
# What it does NOT do (you run these yourself, after the script finishes):
#   - certbot (it's interactive, asks for an email and ToS)
#   - any git operations (clone/commit/push)
#
# Prerequisites:
#   - The project must already exist at $APP_DIR (default /var/www/tejam),
#     i.e. you've already done `git clone` or `scp` before running this.
#   - DNS A record for $DOMAIN must point to this VM's public IP.
#   - You're running as a sudo-capable user (script will re-exec with sudo).
#
# Usage:
#   bash deploy/setup.sh
#   # or override defaults:
#   DOMAIN=16599.lccrm.uz APP_DIR=/var/www/tejam SERVICE_USER=azureuser \
#     bash deploy/setup.sh
#
# Re-running is safe — the script is idempotent.

set -euo pipefail

# ---- Config (override via env) -----------------------------------------------

DOMAIN="${DOMAIN:-16599.lccrm.uz}"
APP_DIR="${APP_DIR:-/var/www/tejam}"
DEFAULT_USER="${SUDO_USER:-$(id -un)}"
SERVICE_USER="${SERVICE_USER:-$DEFAULT_USER}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

# Re-exec with sudo if not already root
if [ "$(id -u)" -ne 0 ]; then
  exec sudo -E DOMAIN="$DOMAIN" APP_DIR="$APP_DIR" SERVICE_USER="$SERVICE_USER" \
    PYTHON_BIN="$PYTHON_BIN" bash "$0" "$@"
fi

if [ -z "$SERVICE_USER" ] || [ "$SERVICE_USER" = "root" ]; then
  echo "ERROR: SERVICE_USER must be a non-root user. Set it explicitly:" >&2
  echo "       SERVICE_USER=azureuser bash deploy/setup.sh" >&2
  exit 1
fi

if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  echo "ERROR: User '$SERVICE_USER' does not exist on this system." >&2
  exit 1
fi

echo "==================================================================="
echo "  Tejam deploy"
echo "  Domain:       $DOMAIN"
echo "  App dir:      $APP_DIR"
echo "  Service user: $SERVICE_USER"
echo "==================================================================="
echo

if [ ! -d "$APP_DIR/backend" ] || [ ! -d "$APP_DIR/frontend" ]; then
  echo "ERROR: $APP_DIR does not contain backend/ and frontend/." >&2
  echo "       Clone or scp the project there first, then re-run." >&2
  exit 1
fi

# Make sure the service user owns the app dir
chown -R "$SERVICE_USER:$SERVICE_USER" "$APP_DIR"

# ---- 1. System packages ------------------------------------------------------

echo "==> Installing system packages..."
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-venv python3-pip \
    nginx certbot python3-certbot-nginx \
    git curl ufw build-essential

# Node.js 20
NODE_OK=0
if command -v node >/dev/null 2>&1; then
  NODE_MAJOR=$(node -v | sed 's/^v//' | cut -d. -f1)
  if [ "$NODE_MAJOR" -ge 20 ]; then
    NODE_OK=1
  fi
fi
if [ "$NODE_OK" -ne 1 ]; then
  echo "==> Installing Node.js 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi

echo "    python: $($PYTHON_BIN --version)"
echo "    node:   $(node --version)"
echo "    nginx:  $(nginx -v 2>&1)"

# ---- 2. Backend venv ---------------------------------------------------------

echo "==> Setting up Python venv..."
sudo -u "$SERVICE_USER" $PYTHON_BIN -m venv "$APP_DIR/backend/venv"
sudo -u "$SERVICE_USER" "$APP_DIR/backend/venv/bin/pip" install --upgrade pip
sudo -u "$SERVICE_USER" "$APP_DIR/backend/venv/bin/pip" install -r "$APP_DIR/backend/requirements.txt"

# ---- 3. .env -----------------------------------------------------------------

ENV_FILE="$APP_DIR/backend/.env"
ENV_NEEDS_EDIT=0
if [ ! -f "$ENV_FILE" ]; then
  echo "==> Creating $ENV_FILE with auto-generated secrets..."
  SECRET=$($PYTHON_BIN -c "import secrets; print(secrets.token_hex(32))")
  JWT=$($PYTHON_BIN -c "import secrets; print(secrets.token_hex(32))")
  cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy/setup.sh
SECRET_KEY=$SECRET
JWT_SECRET_KEY=$JWT

# Fill these in with real values, then: sudo systemctl restart tejam
GEMINI_API_KEY=
STRIPE_SECRET_KEY=

FRONTEND_URL=https://$DOMAIN

# Leave at 1 for the very first start so the database gets seeded.
# After the first successful boot, change to 0 and restart the service.
SEED_DB=1
EOF
  chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  ENV_NEEDS_EDIT=1
else
  echo "==> $ENV_FILE already exists — leaving it alone."
fi

# ---- 4. Frontend env + build -------------------------------------------------

# frontend/.env is gitignored, so create a stub if it doesn't exist.
# VITE_* variables are baked into the bundle at build time, so this file MUST
# exist BEFORE `npm run build`.
FRONTEND_ENV="$APP_DIR/frontend/.env"
if [ ! -f "$FRONTEND_ENV" ]; then
  echo "==> Creating $FRONTEND_ENV stub..."
  cat > "$FRONTEND_ENV" <<'EOF'
# Frontend build-time variables (baked into the bundle).
# After editing this file, you MUST rebuild: cd /var/www/tejam/frontend && npm run build
#
# Get a Yandex Maps JavaScript API key at https://developer.tech.yandex.ru/
# Restrict it to your domain for safety.
VITE_YANDEX_MAPS_API_KEY=
EOF
  chown "$SERVICE_USER:$SERVICE_USER" "$FRONTEND_ENV"
  echo
  echo "!! NOTE: $FRONTEND_ENV was created empty."
  echo "!! Fill in VITE_YANDEX_MAPS_API_KEY (and any other VITE_* keys),"
  echo "!! then re-run this script (or just: cd $APP_DIR/frontend && npm run build)."
  echo
fi

echo "==> Building frontend (npm install + npm run build)..."
sudo -u "$SERVICE_USER" bash -c "cd '$APP_DIR/frontend' && npm install && npm run build"

if [ ! -f "$APP_DIR/frontend/dist/index.html" ]; then
  echo "ERROR: frontend build did not produce dist/index.html" >&2
  exit 1
fi

# ---- 5. systemd service ------------------------------------------------------

echo "==> Installing systemd service..."
cat > /etc/systemd/system/tejam.service <<EOF
[Unit]
Description=Tejam Flask backend (Gunicorn)
After=network.target

[Service]
User=$SERVICE_USER
Group=www-data
WorkingDirectory=$APP_DIR/backend
Environment="PATH=$APP_DIR/backend/venv/bin"
EnvironmentFile=$APP_DIR/backend/.env
ExecStart=$APP_DIR/backend/venv/bin/gunicorn \\
    --workers 3 \\
    --bind 127.0.0.1:5000 \\
    --access-logfile - \\
    --error-logfile - \\
    "app:create_app()"
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable tejam
systemctl restart tejam

# Give it a moment to bind, then check
sleep 3
if ! systemctl is-active --quiet tejam; then
  echo "ERROR: tejam.service failed to start. Recent logs:" >&2
  journalctl -u tejam -n 50 --no-pager >&2
  exit 1
fi
echo "    tejam.service: active"

# ---- 6. Nginx ----------------------------------------------------------------

echo "==> Installing Nginx site..."
cat > /etc/nginx/sites-available/tejam <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    client_max_body_size 10M;

    root $APP_DIR/frontend/dist;
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /api/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
    }

    location /uploads/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

ln -sf /etc/nginx/sites-available/tejam /etc/nginx/sites-enabled/tejam
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# ---- 7. Firewall (UFW) -------------------------------------------------------

echo "==> Configuring UFW..."
ufw allow OpenSSH >/dev/null || true
ufw allow 'Nginx Full' >/dev/null || true
if ! ufw status | grep -q "Status: active"; then
  yes | ufw enable >/dev/null || true
fi

# ---- Done --------------------------------------------------------------------

echo
echo "==================================================================="
echo "  Base deploy complete."
echo "==================================================================="
echo
echo "Quick test (HTTP, before HTTPS):"
echo "    curl -I http://$DOMAIN"
echo
echo "Next steps:"
echo
echo "  1. Get a real HTTPS certificate from Let's Encrypt:"
echo "         sudo certbot --nginx -d $DOMAIN"
echo "     (interactive — enter your email, agree to ToS, choose REDIRECT)"
echo
if [ "$ENV_NEEDS_EDIT" -eq 1 ]; then
echo "  2. Edit $ENV_FILE and fill in:"
echo "         GEMINI_API_KEY=..."
echo "         STRIPE_SECRET_KEY=..."
echo "     Then restart the backend:"
echo "         sudo systemctl restart tejam"
echo
fi
echo "  3. After the site is verified working in the browser, set SEED_DB=0"
echo "     in $ENV_FILE and restart:"
echo "         sudo systemctl restart tejam"
echo
echo "Logs:"
echo "    sudo journalctl -u tejam -f          # backend"
echo "    sudo tail -f /var/log/nginx/error.log # nginx errors"
echo
